services:
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_ARGS=--loadmodule /opt/redis-stack/lib/redistimeseries.so

  token-analytics:
    build:
      context: .
      dockerfile: Dockerfile.analytics
      target: token-analytics
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

  redis-timeseries-service:
    build:
      context: .
      dockerfile: Dockerfile.timeseries
    ports:
      - "8081:8081"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

volumes:
  redis_data:
