services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data
    command: redis-server --protected-mode no --loadmodule /opt/redis-stack/lib/redistimeseries.so
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  token-analytics:
    build:
      context: .
      dockerfile: Dockerfile.analytics
      target: token-analytics
    ports:
      - "8082:8080"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_ADDR=redis:6379

  redis-timeseries-service:
    build:
      context: .
      dockerfile: Dockerfile.timeseries
    ports:
      - "8085:8081"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_ADDR=redis:6379

volumes:
  redis_data:
